[tool.poetry]
name = "pelican-photos"
version = "1.4.0"
description = "Add a photo or a gallery of photos to an article"
authors = ["Joaquim Baptista <pxquim@gmail.com>"]
license = "AGPL-3.0"
readme = "README.md"
keywords = ["pelican", "plugin", "photos"]
repository = "https://github.com/pelican-plugins/photos"
documentation = "https://docs.getpelican.com"
packages = [
    { include = "pelican" },
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Framework :: Pelican",
    "Framework :: Pelican :: Plugins",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.urls]
"Funding" = "https://donate.getpelican.com/"
"Issue Tracker" = "https://github.com/pelican-plugins/photos/issues"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
pelican = ">=4.5"
piexif = {version = "^1.1.3", optional = true}
Pillow = ">=10.0.1"

[tool.poetry.group.dev.dependencies]
black = "^23"
flake8 = "^4.0"
flake8-black = "^0.3.0"
invoke = "^2.1"
isort = "^5.11.5"
# https://github.com/Python-Markdown/markdown/issues/1203
markdown = [
    {version = "<=3.3.4", python = "<3.10"},
    {version = "^3.2", python = "^3.10"}
]
pytest = "^7.0"
pytest-cov = "^3.0"
pytest-sugar = "^0.9"

[tool.poetry.extras]
markdown = ["markdown"]

[tool.autopub]
project-name = "Photos"
git-username = "botpub"
git-email = "52496925+botpub@users.noreply.github.com"
append-github-contributor = true

[tool.isort]
# Maintain compatibility with Black
profile = "black"
multi_line_output = 3

# Sort imports within their section independent of the import type
force_sort_within_sections = true

# Designate "pelican" as separate import section
known_pelican = "pelican"
sections = "FUTURE,STDLIB,THIRDPARTY,PELICAN,FIRSTPARTY,LOCALFOLDER"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
